### ISSUE TITLE
Extension permanently disabled

### ISSUE THREAD

**Issue by BobbyMcGowan** [faymaz/dexcom#1]
Hello, I recently tried this extension however am running into an issue where it is constantly disabled. 
Here is the log that the extensions app provides me with.

```
The settings of extension dexcom@faymaz had an error:

ImportError: Unable to load file from: resource:///org/gnome/shell/extensions/extensionUtils.js (The resource at “/org/gnome/shell/extensions/extensionUtils.js” does not exist)

Stack trace:
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  


```

I'm running on EndeavourOS using GNOME 47.1 and all my packages are up-to-date

**Comment by faymaz** [comment]
Thanks for reporting this issue. I'm happy to inform you that this has been fixed in the latest version of the extension.

The extension now properly handles both US and Non-US regions for Dexcom Share connections:

- US region uses: https://share2.dexcom.com
- Non-US region uses: https://shareous1.dexcom.com

The region selection can be configured in the extension settings:
1. Open GNOME Extensions app
2. Click the settings gear icon for "Dexcom Blood Glucose Monitor"
3. Select your region (US or Non-US)

Please install the latest version from GNOME Extensions website [once approved] or from the main branch of this repository to get this fix.

If you're still experiencing any issues with region selection, please let me know and include:
- Your selected region
- Any error messages you see in the logs (`journalctl /usr/bin/gnome-shell -f -o cat`)
- Your Dexcom Share server location

Closing this issue as fixed, but feel free to reopen if you encounter any problems.
